### ISSUE TITLE
BACKEND_DEFAULT_AUTHORIZATION feature flag to allow any user to create Own resources with no extra authorization

### ISSUE THREAD

**Issue by aicampbell** [Calipsoplus/calipsoplus-frontend#87]
GIVEN I am at the **RESOURCES page**
AS any **logged in user**
WHEN I see the **Own Resources section**
AND the flag **BACKEND_DEFAULT_AUTHORIZATION value is 1 on the Settings file**
THEN I should **always be able to create my own resources**.

GIVEN I am at the **RESOURCES page**
AS any **logged in user**
WHEN I see the **Own Resources section**
AND the flag **BACKEND_DEFAULT_AUTHORIZATION value is 0 on the Settings file**
THEN the system **should check the BACKEND_UO_IS_AUTHORIZED endpoint whether the logged in user is authorized or not to manage own resources.**

**Comment by andygotz** [comment]
We need this so I am removing the "invalid" label ...

I don't see why we can allow users to create containers if they have data but not if they don't have data. @dsanchez-cells and @dsalvat-cells  can you explain why this is a potential problem.

**Comment by ghost** [comment]
Hi @andygotz,

Authorization of this feature is already managed by a flag on the application, called BACKEND_UO_IS_AUTHORIZED, which intends to be an endpoint to discover whether a user is authorized to use internal resources with no experiment attached.

In our case, removing this Authorization mechanism would imply that any user who creates an account in our User Office would have automatically access to our resources with no additional filter.

This filter would also allow us to manage the access for a certain user who may be misusing the resources we are providing.

Our suggestion was, if you do not want to have any authorization mechanism, we can include a way to either make this BACKEND_UO_IS_AUTHORIZED return true by default, or adding an additional setting variable to bypass it, letting each facility decide what is best.

In our conversation with @aicampbell last week, I may have misinterpret what was the point. In any case, what I meant by removing the restriction of 1 user - 1 machine is defined in this issue:  https://github.com/Calipsoplus/calipsoplus-frontend/issues/89

Would this solution make sense to you?

**Comment by andygotz** [comment]
@dsalvat-cells thanks a lot for the explanation. It sounds reasonable. Let me discuss it with @aicampbell to see if I have misunderstood what the problem is.

One difference might be that seeing as we are using OpenID to authenticate we only have bona fide ESRF users. However you are right that if some external user creates an UmbrellaID account they could get access to running containers without being an ESRF user. Which I agree could be an issue. This assumes that the portal is accessible from internet. Currently it is only on intranet.

**Comment by ghost** [comment]
Hi @andygotz ,

thanks for your reply. Since there is at least a use case in which this kind of authorization needs to be bypassed, we could transform this issue into another one that fits better to your needs, such as **Adding a new flag to authorize use of resources by default**.  That would leave each facility to decide what strategy to use.

Please, let me know your thoughts and we can to the adjustments.

**Comment by aicampbell** [comment]
@dsalvat-cells  Could you please implement a flag to allow the use of resources by default?

**Comment by ghost** [comment]
Hi @aicampbell,
I will change the requirements definition, so it fits better to the clarified need. We will plan the implementation for next sprint (starts next week).

Thanks,

Daniel

**Comment by aicampbell** [comment]
@dsalvat-cells So by default, we can allow anyone with an account to create a resource. But we also have the option to check if the user has permission using some API?
I think that is a good solution

**Comment by acampsm** [comment]
This could be close so is an issue about calipso-backend (79).
